[package]
name = "godot-cli"
version = "1.0.0"
edition = "2021"

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true

[dependencies]
colored = "2.1.0"
confy = "0.6.1"
serde = { version = "1.0.199", features = ["derive"] }
